<a href="https://colab.research.google.com/github/siddhidamkondwar/Practical_Machine_Learning/blob/main/ML_4_6_26_DAY3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import linalg
import scipy
from scipy import stats
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
from collections import Counter
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'stackloss')

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

In [ ]:
# Creating an instance for the function
regr1 = LinearRegression()

In [ ]:
regr1.fit(x_train,y_train)

LinearRegression()

In [ ]:
regr1.intercept_

np.float64(-33.281344575611186)

In [ ]:
regr1.coef_

array([ 0.70013521,  1.34985785, -0.22974125])

In [ ]:
regr1.feature_names_in_

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

In [ ]:
regr1.score(x_train,y_train)

0.9080862696530125

In [ ]:
regr1.predict(x_test)

array([10.83134469, 14.08460126, 10.34327252])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scl = StandardScaler()

In [ ]:
x_train = scl.fit_transform(x_train)

In [ ]:
x_test = scl.transform(x_test)

In [ ]:
regr2 = LinearRegression()

In [ ]:
regr2.fit(x_train,y_train)

LinearRegression()

In [ ]:
regr2.intercept_

np.float64(18.666666666666668)

In [ ]:
regr2.coef_

array([ 6.19332814,  4.40861726, -0.90286981])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scl = StandardScaler()

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

In [ ]:
x_train = scl.fit_transform(x_train)

In [ ]:
x_test = scl.transform(x_test)

In [ ]:
x_train = pd.DataFrame(x_train,columns=['AirFlow','WaterTemp','AcidConc'])

In [ ]:
x_test = pd.DataFrame(x_test,columns=['AirFlow','WaterTemp','AcidConc'])

In [ ]:
regr2 = LinearRegression()

In [ ]:
regr2.fit(x_train,y_train)

LinearRegression()

In [ ]:
regr2.intercept_   # intercept

np.float64(18.666666666666668)

In [ ]:
regr2.coef_    # coefficients

array([ 6.19332814,  4.40861726, -0.90286981])

In [ ]:
regr2.feature_names_in_

array(['AirFlow', 'WaterTemp', 'AcidConc'], dtype=object)

# *FEATURE SCALING:*

In [ ]:
df = pd.DataFrame({'Values':[3,6,5,1,6,8,3,8,9,4]})

In [ ]:
df['StdScale'] = (df.Values-np.mean(df.Values))/np.std(df.Values,ddof=1)

In [ ]:
df

   Values  StdScale
0       3 -0.890045
1       6  0.270883
2       5 -0.116093
3       1 -1.663997
4       6  0.270883
5       8  1.044835
6       3 -0.890045
7       8  1.044835
8       9  1.431811
9       4 -0.503069

In [ ]:
(6-np.mean(df.Values))/np.std(df.Values,ddof=1)

np.float64(0.2708831922193681)

In [ ]:
df['MinMax'] = (df.Values - min(df.Values))/(max(df.Values)-min(df.Values))

In [ ]:
df

   Values  StdScale  MinMax
0       3 -0.890045   0.250
1       6  0.270883   0.625
2       5 -0.116093   0.500
3       1 -1.663997   0.000
4       6  0.270883   0.625
5       8  1.044835   0.875
6       3 -0.890045   0.250
7       8  1.044835   0.875
8       9  1.431811   1.000
9       4 -0.503069   0.375

In [ ]:
df['Robust'] = (df.Values - np.median(df.Values))/(np.percentile(df.Values,75)-np.percentile(df.Values,25))

In [ ]:
df

   Values  StdScale  MinMax    Robust
0       3 -0.890045   0.250 -0.588235
1       6  0.270883   0.625  0.117647
2       5 -0.116093   0.500 -0.117647
3       1 -1.663997   0.000 -1.058824
4       6  0.270883   0.625  0.117647
5       8  1.044835   0.875  0.588235
6       3 -0.890045   0.250 -0.588235
7       8  1.044835   0.875  0.588235
8       9  1.431811   1.000  0.823529
9       4 -0.503069   0.375 -0.352941

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'salaries')

df = df[['yrs_service','gender','salary']]

gender_dum = pd.get_dummies(df.gender,drop_first=True).astype(int)

df = pd.concat([df,gender_dum], axis=1)

df = df.drop('gender', axis=1)


# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('salary', axis=1),df.salary, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     21.52
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           1.75e-09
Time:                        12:18:01   Log-Likelihood:                -3698.4
No. Observations:                 317   AIC:                             7403.
Df Residuals:                     314   BIC:                             7414.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
yrs_service   701.6382    125.946      5.571      0.000     453.834     949.442
Male         1.368e+04   5434.664      2.517      0.012    2985.362    2.44e+04
const        8.857e+04   5285.500     16.757      0.000    7.82e+04     9.9e+04
==============================================================================
Omnibus:                       28.103   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.160
Skew:                           0.696   Prob(JB):                     3.82e-08
Kurtosis:                       3.804   Cond. No.                         99.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
#null hypothesis : With respect to feamalles if a male selelcted then it does not influence salalry
#for the constant row H0 = c =0  since the p value =0 we reject the null hypothesios
#constant term influences salary
#const = 88570 indicates the salry of a person for who years_service =0 and male =0 which means that the gender is feamale ()
#the starting sal of male = 88570 + 13680

In [ ]:
df = pd.read_excel('SalesData.xlsx')


region_dum = pd.get_dummies(df['Region'],drop_first=True).astype(int)

df = pd.concat([df,region_dum], axis=1)

df = df.drop('Region', axis=1)


# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('Sales', axis=1),df.Sales, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.887
Method:                 Least Squares   F-statistic:                     1889.
Date:                Thu, 04 Jun 2026   Prob (F-statistic):               0.00
Time:                        12:18:02   Log-Likelihood:                -5940.0
No. Observations:                1200   AIC:                         1.189e+04
Df Residuals:                    1194   BIC:                         1.192e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Ad_Budget      3.4866      0.037     93.243      0.000       3.413       3.560
Store_Size     0.0185      0.001     24.302      0.000       0.017       0.020
North         -4.0818      2.830     -1.442      0.149      -9.634       1.471
South         10.7994      2.770      3.899      0.000       5.365      16.234
West          -5.9182      2.768     -2.138      0.033     -11.349      -0.488
const         68.6151      3.535     19.409      0.000      61.679      75.551
==============================================================================
Omnibus:                        4.762   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.092   Jarque-Bera (JB):                3.820
Skew:                          -0.010   Prob(JB):                        0.148
Kurtosis:                       2.724   Cond. No.                     1.41e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
#categorical regression : const term indicates the value of the response when the continious varialbes =0 and the categorical variables are set at equal to referance level